version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate-limiting-app
    command: >
      sh -c "python app.py"
    ports:
    - "8000:5000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    hostname: redis

